export const AUTH_LOADING = "AUTH_LOADING";
export const SIGNUP_LOGIN_SUCCESS = "SIGNUP_LOGIN_SUCCESS";
export const SIGNUP_LOGIN_FAILURE = "SIGNUP_LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const USER_LOADED = "USER_LOADED";
